### ISSUE TITLE
FPS in GPU environment

### ISSUE THREAD

**Issue by giranntu** [tpys/face-everthing#10]
Hi author, 
Thanks for the great work for aligning all the state-of-the-art project. 

Since I only get slow FPS like 4 FPS in Quadro M5000 GPU card.
I am wondering the FPS you get in your environment?
Or how could we improve by modify the parameters. 

Also I viewed all issues, can't make the model recognize customize training data. 
Should you provide the hint how to improve it?

This would be the awesome repo if we got the last milestone for this!
Thanks for the kindly support.

**Comment by tpys** [comment]
@giranntu 
1.Improve FPS, currently the time consuming part is face alignment, instead use openpose face alignment algorithm, we can train a small and fast model,  please reference [https://github.com/1adrianb/face-alignment](url) 
2.recognize customize data,  retrain the model with your data or fine tuning on your data can get better result, moreover I think large training data and triplet loss training is the ultimate way.
